#!/usr/bin/env bash
set -Eeuo pipefail
ROOT=/mbzz_ssd/modelbest_v0.19
RUN_ROOT=${ROOT}/v019_compat_100step_loss_scale_2p32_20260915/${V019_ATTEMPT:-preflight}
mkdir -p "${RUN_ROOT}"
export MEGATRON_PATH=${ROOT}/Megatron-LM
PATCH=${ROOT}/megatron-lm-musa-patch
export PYTHONPATH=${ROOT}/emerging-optimizers
export PRETRAIN_FILE=${PATCH}/examples/minicpm5/pretrain_minicpm5_musa.py
export EP_SIZE=8 CP_SIZE=8 EXPERT_TP_SIZE=1 GPUS_PER_NODE=8
export TRAIN_ITERS=100 LR_WARMUP_ITERS=1000 SAVE_INTERVAL=999999
export INITIAL_LOSS_SCALE=4294967296
export SEQ_LENGTH=131072 MAX_POSITION_EMBEDDINGS=131072 SEED=1234
export ALLOW_RANDOM_INIT=1 RESUME=0 NO_SAVE=1
export SAVE_DIR=${RUN_ROOT}/output TENSORBOARD_DIR=${RUN_ROOT}/tensorboard
export OUTPUT_LOG_ROOT=${RUN_ROOT}/output_log
export LOG_TEE_LEVEL=3 DISABLE_RECOMPUTE=1
export ENABLE_DEEPEP=0 USE_DEEPEP_ACE=0 DEEPEP_ACE_DYNAMIC_TOKEN_NUM=1
export ENABLE_CE_TE=1 ENABLE_MANUAL_GC=1 ENABLE_ROPE_FUSION=1
export ENABLE_MOE_ROUTER_FUSION=1 ENABLE_GRAD_ACCUM_FUSION=1 ENABLE_DEEPEP_ENV=1
export ENABLE_RMSNORM_FUSION=0 USE_GROUPED_GEMM=1 MOE_DEEPEP_NUM_SMS=56
export USE_SPAN_BASED_ATTN=1 USE_FLASH_ATTN=1 OPTIMIZER=muon
export MUON_BATCH_NS=0 MUON_DP1_LOW_MEMORY=0 MUON_FUSED_POINTWISE=0
export MUSA_TE_PADDED_METADATA_NO_SYNC=0 MUSA_FUSED_ROUTE_CONVERSION=0
export MUON_TE_EXPERT_BATCH_NS=0 ENABLE_FLEX_SHARED_EXPERT_EAGER=0
export ENABLE_SHARED_EXPERT_OVERLAP=0 NVTE_BATCH_MHA_P2P_COMM=0 ENABLE_PROFILER=0
export MCCL_MIN_NCHANNELS=16 MCCL_MAX_NCHANNELS=16 MCCL_BUFFSIZE=16777216
export PYTHONDONTWRITEBYTECODE=1
export MEGATRON_LOG_RUNTIME_PATHS=1
bash ${ROOT}/train_16a3b_v019_isolated.sh "${RUN_ROOT}" "${PATCH}" \
  minicpm5_v019_tp2_pp1_cp8_ep8_dp1_seq131072_gbs32_seed1234 \
  ${ROOT}/hostfile_v019_2node \
  ${ROOT}/data/minicpm5_real_part00071_text_document \
  2 1 1 32 ${ROOT}/models/ckpt v019_100step_loss_scale_2p32_${V019_ATTEMPT:-preflight} 30629
